# .gitlab-ci.yml

stages:
  - test
  - build
  # - deploy

variables:
  REGISTRY: mdtxcontreg.azurecr.io
  USER: mdtxcontreg
  PASSWORD: aojdufoq8Eo5Ay2rb79fYTN+oHccBqK3

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet restore
    - dotnet test PdfGenerator.Test/PdfGenerator.Test.csproj

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login $REGISTRY -u $USER -p $PASSWORD
    - docker build -t $REGISTRY/my-image:${CI_COMMIT_SHORT_SHA} .
    - docker push $REGISTRY/my-image:${CI_COMMIT_SHORT_SHA}

# deploy:
#   stage: deploy
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker login $REGISTRY -u $USER -p $PASSWORD
#     - docker pull $REGISTRY/my-image:${CI_COMMIT_SHORT_SHA}
#     - # Add deployment commands here

rules:
  - if: '$CI_COMMIT_BRANCH == "development" && $CI_OPEN_MERGE_REQUESTS'
    changes:
      - PdfGenerator.Core/**
      - PdfGenerator.Application/**
      - PdfGenerator.Infrastructure/**
      - PdfGenerator.Test/**
      - PdfGenerator.WebApi/**
    when: always
  - if: '$CI_COMMIT_BRANCH != "development"'
    changes:
      - PdfGenerator.Core/**
      - PdfGenerator.Application/**
      - PdfGenerator.Infrastructure/**
      - PdfGenerator.Test/**
      - PdfGenerator.WebApi/**
    when: never