global using NUnit.Framework;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Moq;
global using PdfGenerator.Infrastructure;
global using AutoMapper;
global using PdfGenerator.Application.Commands;
global using PdfGenerator.Application.Commands.Validators;
global using PdfGenerator.Application.Handlers; 
global using PdfGenerator.Test.HtmlTemplateToPdf.Utilities;
global using Assert = NUnit.Framework.Assert;
