name: Deploy to Docker Hub

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: srestituyo/HtmlTemplateToPdfGenerator

      - name: Build and push Docker image
        run: |
          docker build -t srestituyo/html-template-pdf-generator:${{ github.sha }} .
          docker tag srestituyo/html-template-pdf-generator:${{ github.sha }} srestituyo/html-template-pdf-generator:latest
          docker login -u srestituyo -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push srestituyo/html-template-pdf-generator:latest

