name: Deploy to Azure Container Registry

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-docker@v1

      - name: Login to Docker registry
        run: docker login ${{ secrets.REGISTRY }} -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY }}/htmltemplatetopdf:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY }}/htmltemplatetopdf:${{ github.sha }}