name: Deploy to Azure Container Registry

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: your-username/HtmlTemplateToPdfGenerator

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY }}/htmltemplatetopdf:${{ github.sha }} .
          docker login ${{ secrets.REGISTRY }} -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
          docker push ${{ secrets.REGISTRY }}/htmltemplatetopdf:${{ github.sha }}
